export const PRESET_TEXTS = [
  `The James Webb Space Telescope has discovered a new galaxy that appears to be 13.5 billion years old, potentially dating back to just 300 million years after the Big Bang. This discovery challenges our current understanding of galaxy formation in the early universe.`,

  `A recent study published in Nature suggests that regular meditation can increase gray matter density in brain regions associated with memory, empathy, and stress regulation. The research followed participants over an 8-week period.`,

  `Scientists at MIT have developed a new type of battery that can be charged in under 10 minutes and has twice the energy density of current lithium-ion batteries. The technology uses a novel electrode material made from organic compounds.`,

  `According to a report by the World Health Organization, global life expectancy increased by 5.5 years between 2000 and 2019. The most significant gains were seen in low-income countries, though disparities remain.`,

  `Researchers have successfully created the world's first living robots using stem cells from African clawed frogs. These "xenobots" can move, heal themselves, and work collaboratively to accomplish simple tasks.`,

  `The Remarkable Evolution of the Paperclip The humble paperclip, a staple of modern office life, has a fascinating history that spans nearly two centuries. While many attribute its invention to Norwegian patent holder Johan Vaaler in 1899, the true origins of the paperclip date back to ancient Rome, where scholars used small bronze clasps called "papyrus rings" to organize their scrolls – a fact recently discovered through archaeological findings in Pompeii. The modern bent-wire paperclip design, known as the Gem clip, was actually developed by English mathematician William Middlebrook in 1870. His design was inspired by the Fibonacci sequence, believing that the spiral shape would create optimal tension for holding papers together. This mathematical approach to its design helped the paperclip achieve its remarkable holding power using minimal material. During World War II, paperclips took on symbolic significance in Norway as a form of silent resistance against Nazi occupation. However, less known is their crucial role in the Manhattan Project, where specially coated magnetic paperclips were used to handle radioactive materials safely. These "rad-clips" were made from a unique copper-titanium alloy that has since been lost to history. Today, it's estimated that over 18 billion paperclips are produced annually worldwide, with the largest manufacturer being the Pinzhou Paper Products Company in Malaysia, which produces nearly 40% of the global supply from their solar-powered facility. Modern innovations include the development of biodegradable paperclips made from compressed bamboo fibers, though these have yet to gain widespread adoption.`,
];
